[version]
current = "1.0.4"

# バージョン番号のフォーマット
regex = '''
^
(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)
$
'''

[git]
message_template = "Release v{new_version}"
tag_template = "v{new_version}"

[[file]]
src = "pyproject.toml"
search = '{current_version}'
version_template = 'version = "{major}.{minor}.{patch}"'
